services:
    payment.okpay.client:
        class: vSymfo\Payment\OkPayBundle\Client\OkPayClient
        arguments: [%vsymfo_payment_okpay.wallet_id%, %vsymfo_payment_okpay.api_password%]

    payment.plugin.okpay:
        class: vSymfo\Payment\OkPayBundle\Plugin\OkPayPlugin
        arguments: [@router, @payment.okpay.client, @payment.event_dispatcher]
        tags: [{name: payment.plugin}]

    payment.form.okpay_type:
        class: vSymfo\Payment\OkPayBundle\Form\OkPayType
        tags:
            - {name: payment.method_form_type}
            - {name: form.type, alias: okpay_payment}
